allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@4.1.10'
  - '@vitest/expect@4.1.10'
  - '@vitest/mocker@4.1.10'
  - '@vitest/pretty-format@4.1.10'
  - '@vitest/runner@4.1.10'
  - '@vitest/snapshot@4.1.10'
  - '@vitest/spy@4.1.10'
  - '@vitest/utils@4.1.10'
  - eslint-plugin-jsdoc@63.0.12
  - vitest@4.1.10
  - '@types/node@26.1.1'
  - '@vue/language-core@3.3.7'
  - vue-tsc@3.3.7
  - '@module-federation/bridge-react-webpack-plugin@2.7.0'
  - '@module-federation/cli@2.7.0'
  - '@module-federation/dts-plugin@2.7.0'
  - '@module-federation/enhanced@2.7.0'
  - '@module-federation/error-codes@2.7.0'
  - '@module-federation/inject-external-runtime-core-plugin@2.7.0'
  - '@module-federation/managers@2.7.0'
  - '@module-federation/manifest@2.7.0'
  - '@module-federation/rspack@2.7.0'
  - '@module-federation/runtime-core@2.7.0'
  - '@module-federation/runtime-tools@2.7.0'
  - '@module-federation/runtime@2.7.0'
  - '@module-federation/sdk@2.7.0'
  - '@module-federation/third-party-dts-extractor@2.7.0'
  - '@module-federation/webpack-bundler-runtime@2.7.0'
